### ISSUE TITLE
migrator_cli_deploy.jar does not build with bazel 0.27.0

### ISSUE THREAD

**Issue by alexanderilyin** [wix/exodus#17]
```
git clone git@github.com:wix/exodus.git
cd exodus
```
```
➜  exodus git:(master) docker run \
  -e USER="$(id -u)" \
  -u="$(id -u)" \
  -v $PWD:/src/workspace \
  -v /tmp/build_output:/tmp/build_output \
  -w /src/workspace \
  l.gcr.io/google/bazel:0.27.0 \
  --output_user_root=/tmp/build_output \
  build //migrator/wix-bazel-migrator:migrator_cli_deploy.jar

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Option 'ui' is deprecated
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: migrator/wix-bazel-migrator
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (1 packages loaded, 0 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (12 packages loaded, 30 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (19 packages loaded, 264 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (37 packages loaded, 306 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (51 packages loaded, 306 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (59 packages loaded, 322 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (60 packages loaded, 322 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (61 packages loaded, 322 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (61 packages loaded, 322 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (67 packages loaded, 377 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (81 packages loaded, 446 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (99 packages loaded, 485 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (123 packages loaded, 562 targets configured)
Analyzing: target //migrator/wix-bazel-migrator:migrator_cli_deploy.jar (153 packages loaded, 650 targets configured)
ERROR: /tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/protobuf.bzl:130:19: Traceback (most recent call last):
	File "/tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/protobuf.bzl", line 125
		rule(attrs = {"srcs": attr.label_list...()}, <2 more arguments>)
	File "/tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/com_google_protobuf/protobuf.bzl", line 130, in rule
		attr.label(cfg = "host", executable = True, sin..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
INFO: Call stack for the definition of repository 'remotejdk11_linux' which is a http_archive (rule definition at /tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /DEFAULT.WORKSPACE.SUFFIX:199:1
INFO: Call stack for the definition of repository 'remote_java_tools_linux' which is a http_archive (rule definition at /tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /DEFAULT.WORKSPACE.SUFFIX:229:1
ERROR: /tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/io_bazel_rules_scala/scala/scala.bzl:509:5: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors and referenced by '//external:io_bazel_rules_scala/dependency/com_google_protobuf/protobuf_java'
ERROR: Analysis of target '//migrator/wix-bazel-migrator:migrator_cli_deploy.jar' failed; build aborted: Analysis failed
INFO: Elapsed time: 63.728s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (164 packages loaded, 728 targets configured)
FAILED: Build did NOT complete successfully (164 packages loaded, 728 targets configured)
```

**Comment by natansil** [comment]
Sorry about that.
Should be fixed by https://github.com/wix/exodus/commit/951f8a9ddbae9e53ab4d93b991b02a3e71f16d9e
waiting for travis for confirmation...

**Comment by natansil** [comment]
built successfully with bazel 0.27.0 on travis
https://github.com/wix/exodus/pull/19

Additional feedback would be warmly welcomed...

**Comment by natansil** [comment]
@alexanderilyin can I close this issue?

**Comment by alexanderilyin** [comment]
@natansil yes, thanks!
