### ISSUE TITLE
Exodus does not use .maven/maven.config revision

### ISSUE THREAD

**Issue by FelixReuthlingerBMW** [wix/exodus#48]
We are using a one-repo approach, having set and updating the revision via using the ".maven/maven.config" file with content like "-Drevision=1.5.0-844-pr_3512-d269bebd004a4745ba1c1dd0c35548db-SNAPSHOT".

It seems Exodus cannot use this approach for parsing the version, since the log output shows an un-parsed version containing the string "...:pom:${revision}".

I know that I simply can replace this via setting the version explicitly through all maven children, so a workaround might be available. But anyways might be nice if Exodus could also use the maven.config.

Here is the output (note: confidential parts replaced with ***):

 _____              _
|  ___|            | |
| |____  _____   __| |_   _ ___
|  __\ \/ / _ \ / _` | | | / __|    by Wix
| |___>  < (_) | (_| | |_| \__ \
\____/_/\_\___/ \__,_|\__,_|___/    with <3

starting migration with configuration [RunConfiguration(/Users/***/git-bazel/data-management,git@***.git,None,None,true,true,true,false,List(),None,None,None,false,Some(/Users/q370608/.m2),None,None,true,false)]
13:10:00.834 INFO  class=[log]  Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
13:10:00.871 INFO  class=[log]  jetty-6.1.x
13:10:00.918 INFO  class=[log]  Started SocketConnector@0.0.0.0:56433
Exception in thread "main" com.wixpress.build.maven.MissingPomException: Failed to read artifact descriptor for com.***.ad.kpi.target_tracking:metrics:pom:${revision}
	at com.wixpress.build.maven.AetherMavenDependencyResolver$$anonfun$1.applyOrElse(AetherMavenDependencyResolver.scala:131)
	at com.wixpress.build.maven.AetherMavenDependencyResolver$$anonfun$1.applyOrElse(AetherMavenDependencyResolver.scala:130)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recover(Try.scala:230)
	at com.wixpress.build.maven.AetherMavenDependencyResolver.withSession(AetherMavenDependencyResolver.scala:130)
	at com.wixpress.build.maven.AetherMavenDependencyResolver.artifactDescriptorOf(AetherMavenDependencyResolver.scala:56)
	at com.wixpress.build.maven.AetherMavenDependencyResolver.$anonfun$artifactDescriptorStore$1(AetherMavenDependencyResolver.scala:33)
	at scala.collection.Map$WithDefault.default(Map.scala:53)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at com.wixpress.build.maven.AetherMavenDependencyResolver.directDependenciesOf(AetherMavenDependencyResolver.scala:50)
	at com.wixpress.build.maven.AetherMavenDependencyResolver.directDependenciesOf(AetherMavenDependencyResolver.scala:41)
	at com.wix.build.maven.analysis.MavenBuildSystem.withDirectDependencies(MavenBuildSystem.scala:31)
	at com.wix.build.maven.analysis.MavenBuildSystem.$anonfun$modules$1(MavenBuildSystem.scala:19)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at com.wix.build.maven.analysis.MavenBuildSystem.modules(MavenBuildSystem.scala:19)
	at com.wix.build.maven.analysis.SourceModules$.apply(SourceModules.scala:15)
	at com.wix.build.maven.analysis.SourceModules$.of(SourceModules.scala:18)
	at com.wix.bazel.migrator.MigratorInputs.readSourceModules(MigratorInputs.scala:79)
	at com.wix.bazel.migrator.MigratorInputs.sourceModules$lzycompute(MigratorInputs.scala:31)
	at com.wix.bazel.migrator.MigratorInputs.sourceModules(MigratorInputs.scala:31)
	at com.wix.bazel.migrator.MigratorInputs.codeModules$lzycompute(MigratorInputs.scala:32)
	at com.wix.bazel.migrator.MigratorInputs.codeModules(MigratorInputs.scala:32)
	at com.wix.bazel.migrator.MigratorInputs.collectExternalDependenciesUsedByRepoModules(MigratorInputs.scala:89)
	at com.wix.bazel.migrator.MigratorInputs.directDependencies$lzycompute(MigratorInputs.scala:33)
	at com.wix.bazel.migrator.MigratorInputs.directDependencies(MigratorInputs.scala:33)
	at com.wix.bazel.migrator.MigratorInputs.dependencyCollector(MigratorInputs.scala:94)
	at com.wix.bazel.migrator.MigratorInputs.<init>(MigratorInputs.scala:34)
	at com.wix.bazel.migrator.Migrator.<init>(Migrator.scala:20)
	at com.wix.bazel.migrator.PublicMigrator.<init>(Migrator.scala:173)
	at com.wix.bazel.migrator.MigratorApplication$.migrate(MigratorApplication.scala:18)
	at com.wix.bazel.migrator.MigratorApplication$.delayedEndpoint$com$wix$bazel$migrator$MigratorApplication$1(MigratorApplication.scala:14)
	at com.wix.bazel.migrator.MigratorApplication$delayedInit$body.apply(MigratorApplication.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.wix.bazel.migrator.MigratorApplication$.main(MigratorApplication.scala:13)
	at com.wix.bazel.migrator.MigratorApplication.main(MigratorApplication.scala)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.***.ad.kpi.target_tracking:metrics:pom:${revision}
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:276)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:192)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:250)
	at com.wixpress.build.maven.AetherMavenDependencyResolver.$anonfun$artifactDescriptorOf$1(AetherMavenDependencyResolver.scala:56)
	at com.wixpress.build.maven.AetherMavenDependencyResolver.$anonfun$withSession$1(AetherMavenDependencyResolver.scala:130)
	at scala.util.Try$.apply(Try.scala:209)
	... 48 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.***.ad.kpi.target_tracking:metrics:pom:${revision} in repo0 (http://localhost:56433)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:423)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:225)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:202)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:261)
	... 53 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.***.ad.kpi.target_tracking:metrics:pom:${revision} in repo0 (http://localhost:56433)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:499)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:400)
	... 56 more

**Comment by natansil** [comment]
Thank you @FelixReuthlingerBMW for posting the issue. 
We will check if `org.apache.maven.model.io.xpp3.MavenXpp3Reader` can somehow take .maven/maven.config

In the meantime, have you tried replacing all locations on a test branch?
I wonder if you were able to finish the migration successfuly.

Are you building exodus from source? it has a more up-to-date source analyzer.
We are going to release a new version soon.

CC: @or-shachar

**Comment by FelixReuthlingerBMW** [comment]
@natansil unfortunately not, I am still getting a 

Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.***.ad.labeling:lidar-web:pom:2.0.0 in repo0 (http://localhost:50333)

But Maven clean install was run successfully before.
Also the pom is in my local repo: ./com/***/ad/labeling/lidar-web/2.0.0/lidar-web-2.0.0.pom

**Comment by or-shachar** [comment]
Hey @FelixReuthlingerBMW ! :-)
Just to understand - how does a pom file looks like?

something like this? (1)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.wixpress.build</groupId>
    <artifactId>foo</artifactId>
    <version>${revision}</version>
       <dependencies>
        <dependency>
            <groupId>com.wixpress.build</groupId>
            <artifactId>bar</artifactId>
            <version>${project.version}</version>
        </dependency>
     <dependencies>
</project>
```

or (2)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.wixpress.build</groupId>
    <artifactId>foo</artifactId>
    <version>1.0.0-SNAPSHOT</version>
       <dependencies>
        <dependency>
            <groupId>com.wixpress.build</groupId>
            <artifactId>bar</artifactId>
            <version>${revision}</version>
        </dependency>
     <dependencies>
</project>
```
or something else?

**Comment by FelixReuthlingerBMW** [comment]
It is the (1), also reference to parent-pom uses  <version>${revision}</version>

**Comment by natansil** [comment]
The first answer here looks promising: https://stackoverflow.com/questions/11525318/how-do-i-obtain-a-fully-resolved-model-of-a-pom-file

**Comment by FelixReuthlingerBMW** [comment]
Now I am getting to the point where I receive another error: 

Exception in thread "main" java.lang.IllegalArgumentException: org.eclipse.aether.resolution.VersionRangeResolutionException: No versions available for commons-codec:commons-codec:jar:[1.8,2.0) within specified range
===== Please double check that you have VPN on and that you have no typos.
if you REALLY meant to reference this jar and you know it exists even though there IS NO pom,
please rerun the tool with --ignoreMissingDependencies flag at the end =====

But when trying to run like this:
➜  data-management git:(bazel-playtime) java -Xmx12G -Dskip.classpath=false -Dskip.transformation=false -Dlocal.maven.repository.path=/Users/***/.m2/repository  -Dfail.on.severe.conflicts=true -Drepo.root=/Users/***/git-bazel/data-management -Drepo.url=git@***/data-management.git -jar ../exodus/bazel-bin/migrator/wix-bazel-migrator/migrator_cli_deploy.jar --ignoreMissingDependencies
 _____              _
|  ___|            | |
| |____  _____   __| |_   _ ___
|  __\ \/ / _ \ / _` | | | / __|    by Wix
| |___>  < (_) | (_| | |_| \__ \
\____/_/\_\___/ \__,_|\__,_|___/    with <3

Error: Unknown option --ignoreMissingDependencies
Wix Bazel Migrator
Usage: Migrator [options]

  -r, --repo <value>
  -m, --managed-deps-repo <value>

  --repo-git-url <value>
  --codota-token <value>
  --skip-maven <value>
  --skip-analysis <value>
  --skip-transform <value>

  --fail-on-severe-conflicts <value>

  --inter-repo-source-dependency <value>

  --artifactory-token <value>

  --source-dependencies-whitelist <value>

  --additional-deps-by-maven-deps <value>

  --include-server-infra-in-social-mode-set <value>

  --remote-maven-repository-urls <value>
                           comma delimited list of remote maven repositories (like artifactory, nexus)
  --local-maven-repository-path <value>

  --third-party-dependencies-source <value>

  --additional-dependencies-file-path <value>

  --remove-junit5-support <value>

  --support-scala <value>
➜  data-management git:(bazel-playtime)

**Comment by natansil** [comment]
Hi Felix,

Bazel does not support a range of versions for 3rd party.
Do you specify commons-codec dependency in one of your pom files?
If yes, then I suggest to choose one version and move forward.

Let's make sure that Exodus can help you get 80%-90% of the bazel build configurations that you require first, and then worry about the edge cases...

**Comment by FelixReuthlingerBMW** [comment]
Ok will try. In general we use huge dependencyManagement section defining the versions, but of course, someone sneaked out there and had defined another version :)

But regarding the "--ignoreMissingDependencies" the error shown is a bit misleading if the program doesn't support an option like this.

**Comment by FelixReuthlingerBMW** [comment]
But also still after removing one stale older specific version the error remains same. Also the version of <artifactId>commons-codec</artifactId> we use is 1.12 and not one of 1.8 or 2.0 as mentioned in the error message.
It would help a lot if the exception would be caught and a reference to where this information came from could be posted. 
It might be that 3rd party open source dependencies contain conflicting versions, but there we are kind of out of control.
Any suggestions?

**Comment by or-shachar** [comment]
Is `commons-codec` a direct dependencies of one of your modules or transitive dependency?

If it's just a transitive - you might be hitting an issue we have reading the managed deps of the pom.

An easy way to check that would be to add `commons-codec` with the version you want as direct dep

**Comment by FelixReuthlingerBMW** [comment]
A direct dependency is already added, but this one doesn't point to neither of 1.8 nor 2.0.

It is very possible that the dependency is used by other libraries transitively.

**Comment by natansil** [comment]
@felixb-wix for more frequent chatting, I invite you to our Slack Workspace:
https://join.slack.com/t/wix-oss/shared_invite/zt-dmz06ume-eMI3cd93NtGRuMwjaBO0lg
please join #exdous channel.

**Comment by or-shachar** [comment]
Do you see a print during the migration:
```
[WARN] ~~~~~~~ Found conflicts between workspace and maven modules third party dependencies ~~~~~~~
```
or does it fail on exception?

**Comment by FelixReuthlingerBMW** [comment]
Nope, those ones I do not see. Just a bunch of:
"Checksum validation failed, no checksums available"

And yes, it fails on exception: java.lang.IllegalArgumentException (as shown above)

Btw the program does not terminate after the exception, is this intended?

And regarding the Slack, I joined there, but cannot see the channel.

**Comment by natansil** [comment]
@FelixReuthlingerBMW Can you please run Bazel from this branch:
https://github.com/wix/exodus/tree/better-error-message and share the error message with us.
This will help us to investigate the issue.
No rush of course. Whenever you want.

**Comment by FelixReuthlingerBMW** [comment]
The new error message helps to understand, where the issue came from, would really support pushing this change to master :)

**Comment by natansil** [comment]
Great. PR merged.
