### ISSUE TITLE
Exodus fails for protoc files

### ISSUE THREAD

**Issue by aman1k4** [wix/exodus#56]
We use proto generated files and it threw an exception for it

18:25:42.589 INFO  class=[CachingEagerEvaluatingDependencyAnalyzer]  DependencyAnalyzer:allCodeForModule:	 50% done
18:27:34.025 INFO  class=[CachingEagerEvaluatingDependencyAnalyzer]  DependencyAnalyzer:allCodeForModule:	 60% done
    Exception in thread "main" java.lang.RuntimeException: Could not find location of <file generated using proto> in <module>
18:51:02.032 INFO  class=[log]  Stopped SocketConnector@0.0.0.0:51752
	at com.wix.bazel.migrator.analyze.jdk.JavaPSourceFileTracer.traceSourceFile(SourceFileTracer.scala:49)
	at com.wix.bazel.migrator.analyze.jdk.JDKToolsDependencyAnalyzer.$anonfun$toCodePath$1(JDKToolsDependencyAnalyzer.scala:34)
	at scala.Option.map(Option.scala:146)
	at com.wix.bazel.migrator.analyze.jdk.JDKToolsDependencyAnalyzer.toCodePath(JDKToolsDependencyAnalyzer.scala:34)
	at com.wix.bazel.migrator.analyze.jdk.JDKToolsDependencyAnalyzer.convertSingleToCode(JDKToolsDependencyAnalyzer.scala:38)
	at com.wix.bazel.migrator.analyze.jdk.JDKToolsDependencyAnalyzer.$anonfun$convertToCode$1(JDKToolsDependencyAnalyzer.scala:48)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
	at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:252)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:788)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:230)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:461)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:461)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:787)
	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:252)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)

**Comment by aman1k4** [comment]
@natansil Has created a new branch which ignores protoc files. Trying it out now: production_feedback
